### ISSUE TITLE
BAT file is doing some funky things (no clue how to explain it)

### ISSUE THREAD

**Issue by Butterscotch96** [PatnosDD/Cuphead-PS-VITA#9]
<img width="635" alt="Screenshot 2024-11-06 at 10 20 29 PM" src="https://github.com/user-attachments/assets/7d8863f7-39c2-4f86-b7c2-d75ea5e7393f">

**Comment by Butterscotch96** [comment]
If it means anything I'm running it with WINE since the only Windows PC in my house has Windows XP.

**Comment by PatnosDD** [comment]
I am not aware on how Wine works, so i dont think i can help you.

BUT.. You could first check if it even created a zip file with deterministic.exe, and if it exists, maybe try to edit path for xdelta patcher and see how it goes

**Comment by PixelatedKnight** [comment]
Hi I'm also on Linux using wine but I bring different issue i got the files to "build" with the Gog version, and I've moved files like instructed but the app/game is still crashing and i dont understand ps vita crash stuff so i give you the .psp2dmp file
[psp2core-1731221313-0x000007355b-eboot.bin.psp2dmp.zip](https://github.com/user-attachments/files/17690529/psp2core-1731221313-0x000007355b-eboot.bin.psp2dmp.zip)

and for the other user who had funky issues i used the cmd in bottles so I would suggest to try using that instead of raw in the terminal even if I'm wrong about that it's still worth a try

**Comment by PatnosDD** [comment]
The pdp2dmp file isnt that helpful honestly. Since you're using Linux, that might be the issue.
